name: tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.3, 7.4]
        typo3: [^9.5, ^10.4, ^11.2]

    name: P${{ matrix.php }} - T${{ matrix.typo3 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-typo3-${{ matrix.typo3 }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, mbstring
          coverage: none

      - name: Check PHP syntax errors
        run: find . -name \*.php ! -path "./.Build/*" -print0 | xargs -0 -n1 -P4 php -d display_errors=stderr -n -l > /dev/null

      - name: Run TypoScript linter
        run: .Build/bin/typoscript-lint -c .typoscript-lint.yml --fail-on-warnings
